project:
  type: website
  output-dir: docs

website:
  title: "John Kubale"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "Kubale_CV_dec_2023.pdf"
        text: CV
      - href: pubs.qmd
        text: Publications
      - href: "test/index.html"
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

