project:
  type: website
  output-dir: docs

website:
  title: "John Kubale"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "Kubale_CV_july_2024.pdf"
        text: CV
      - href: pubs.qmd
        text: Publications
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



